### PR TITLE
Observe.js and test dir

### PR DESCRIPTION
**Pull request by kingshu**
Added Observe.js
Added test/lsExample with working code.

### CODE REVIEW

**Comment by ChristopherWirtOfficial** [comment]
Crazy Kingshu, don't push all of your bower files.

**Comment by kingshu** [comment]
i thought bower_components/\* was in .gitignore

**Comment by kingshu** [comment]
Oh node_modules/\* was not in gitignore. lol. adding.

**Comment by ChristopherWirtOfficial** [comment]
Or maybe npm install -g, basdflasdflasdflhawefdsa

Christopher Wirt
Cell: 317-727-1690

----- Original Message -----

**Comment by kingshu** [comment]
Global installs are for noobs. Jk, will create another PR soon

**Pull request closed without merging**
